using System.Collections.Generic;

namespace kuarasy.Models.Enums
{
    public enum TSql
    {
        //RELACIONADO COM PRODUTO
        CADASTRAR_PRODUTO,
        LISTAR_PRODUTO,
        CONTAGEM_PRODUTO,
        CONTAGEM_PRODUTO_PESQUISA,
        PESQUISAR_PRODUTO,
        ATUALIZAR_PRODUTO,
        EXCLUIR_PRODUTO,
        CADASTRAR_TAMANHO,
        ULTIMO_REGISTRO_TAMANHO,
        PESQUISAR,
        EXCLUIR_ORIGEM_PRODUTO,
        LISTAR_TIPOS,
        LISTAR_TIPOS_CATEGORIA,
        CONTAGEM_TIPO,
        BUSCAR_CATEGORIA,
        CADASTRAR_ORIGEM_PRODUTO,
        ULTIMO_REGISTRO_PRODUTO,
        //RELACIONA COM ORIGEM
        LISTAR_ORIGEM,
        PESQUISAR_ORIGEM,
        LISTAR_PRODUTOS_ORIGEM,
        //RELACIONA COM A COMPRA
        CADASTRAR_COMPRA,
        CADASTRAR_COMPRA_PRODUTO,
        ULTIMO_REGISTRO_COMPRA
    }
}
